version: '3.9'
# instruction at the end of file

volumes:
  postgres_data:
  static:
  media:
  nginx_conf:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  django:
    image: matakov/redis:latest
    depends_on:
      - db
      - rabbitmq
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/code/nginx/
    entrypoint: /code/entrypoint.sh
    environment:
      - DEBUG=0

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "127.0.0.1:1133:80"
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always

  rabbitmq:
    image: rabbitmq
    restart: always
    env_file:
      - ./.env.prod