# Generated by Django 3.2.3 on 2021-06-14 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210614_0045"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="cash",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=19, verbose_name="Баланс"
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=19,
                        verbose_name="Сумма дохода/Расхода",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "dish",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.dish",
                        verbose_name="Блюдо",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
