# Generated by Django 3.2.3 on 2021-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20210614_1857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=19,
                verbose_name="Введите сумму пополнения",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=19,
                verbose_name="Сумма транзакции",
            ),
        ),
    ]
