# Generated by Django 3.2.3 on 2021-06-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210614_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='dish',
        ),
        migrations.CreateModel(
            name='DishDateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата планируемой подачи блюда')),
                ('is_ready', models.BooleanField(default=False)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.dish')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='dish_date_link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.dishdatelink', verbose_name='Дата и блюдо'),
        ),
    ]
