# Generated by Django 3.2.3 on 2021-06-17 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20210617_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflow",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
