# Generated by Django 3.2.3 on 2021-06-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_cashflow_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Тип блюда")),
                (
                    "picture",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение типа блюда"
                    ),
                ),
            ],
        ),
    ]
