# Generated by Django 3.2.3 on 2021-06-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_dishtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.dishtype",
                verbose_name="Тип блюда",
            ),
        ),
    ]
