# Generated by Django 3.2.3 on 2021-06-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_ingredient_ingredienttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя поставщика"),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение поставщика"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание поставщика")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Телефон поставщика"),
                ),
                (
                    "site",
                    models.CharField(max_length=100, verbose_name="Сайт поставщика"),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Адрес поставщика"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingredient",
            name="supplier",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
