# Generated by Django 3.2.3 on 2021-06-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210621_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_app_online', models.BooleanField(default=True, verbose_name='Главный переключатель приложения. Можем оформлять заказы?')),
            ],
        ),
    ]
