# Generated by Django 3.2.3 on 2021-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_transaction_serving"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                default="Сотрудник", max_length=100, verbose_name="Должность сотрудника"
            ),
        ),
    ]
