# Generated by Django 3.2.3 on 2021-06-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_user_is_notify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="dishes",
                to="main.dishtype",
                verbose_name="Тип блюда",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Цена ингредиента",
            ),
        ),
    ]
