# Generated by Django 3.2.3 on 2021-06-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_auto_20210629_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="ingredients",
                to="main.ingredienttype",
                verbose_name="Тип ингредиента",
            ),
        ),
    ]
