# Generated by Django 3.2.3 on 2021-07-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_ingredient_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishdatelink",
            name="dish",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="dish_date_links",
                to="main.dish",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="supplier",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="ingredients",
                to="main.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientamount",
            name="amount",
            field=models.DecimalField(
                decimal_places=1, max_digits=5, verbose_name="Сколько штук"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="dish_date_link",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="transactions",
                to="main.dishdatelink",
                verbose_name="Дата и блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="serving",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=19,
                verbose_name="Размер порции (0.5, 1, 2)",
            ),
        ),
    ]
